### ISSUE TITLE
Support for megahit

### ISSUE THREAD

**Issue by adityabandla** [metagentools/GraphBin2#1]
Are there plans to support megahit assemblies?

**Comment by Vini2** [comment]
Thanks for the question! We are planning to add support for more assembly tools (including MEGAHIT) in the future. I will keep the issue open until I update the code.

Cheers!

**Comment by zoey-rw** [comment]
Hi! Just wondering if support for Megahit is still a planned feature (in my case, I've already carried out contig assembly with Megahit and binning with MaxBin2 and would like to use GraphBin2 to improve the resulting bins).

**Comment by Vini2** [comment]
Hello @zoey-rw,

We are currently working on integrating MEGAHIT support for GraphBin2. The feature will be available soon.

Cheers!

**Comment by schorlton** [comment]
Hi @Vini2 , thanks for your great work! Wondering if you have any rough code which I could help with to get megahit going? Thanks!

**Comment by npbhavya** [comment]
Can you please add megahit2 to the list of assemblies that graphbin2 could work on. 

Thank you

**Comment by LDoni** [comment]
follow :)

**Comment by fergsc** [comment]
Hi,
Did megahit ever get integrated into GraphBin2?

Thanks
