### ISSUE TITLE
Cannot find gfa2fasta.py

### ISSUE THREAD

**Issue by lewhiteside** [metagentools/GraphBin2#11]
Hi there, Im fairly new to running python scripts so apologies if I have missed something obvious.

I have installed GraphBin2 by first downloading GraphBin2 v1.1, unzipping the file and moving into the GraphBin2 directory.  I then ran the following commands: 

```
conda env create -f environment.yml
conda activate graphbin2
```

Since I am using metaflye to generate contigs, I ran :

`python gfa2fasta.py -h`

However, I get the following error message:

`python: can't open file '/usr/bin/gfa2fasta.py': [Errno 2] No such file or directory`

Could someone please help by pointing me in the direction of where I am going wrong?  Thank you in advance!

**Comment by Vini2** [comment]
Helllo,

I’ll get back to you soon after the holidays!

Thanks!

**Comment by Vini2** [comment]
`gfa2fasta` is no longer available as GraphBin2 now supports original contigs from Flye.

Closing this issue.
