### ISSUE TITLE
prepResult.py produces output with single bin assignment from metabat2 initial binning

### ISSUE THREAD

**Issue by colin-heberling** [metagentools/GraphBin2#13]
I performed the following pre-processing steps:

1. Using the git repository-provided test results from Sim-5G-metaspades:
2. Ran Metabat2 on the contigs using the option --saveCls in order to save contig bin assignments to file (.tsv by default).
3. Used sed to convert bin assignments file to .csv

Running graphbin2 on these results gives the following error:
`ERROR - Please make sure that you have provided the correct assembler type and the correct path to the binning result file in the correct format.`

Ran the provided utility script prepResult.py on the metabat2 bin assignments as follows:
`python ../../support/prepResult.py --binned $(pwd) --output . --prefix metabat2`

Thus, the reformatted initial binning results are in the file `metabat2_initial_contig_bins.csv`, but every single contig has a bin assignment of '1', when in the original file there are 7 bins (one of which is likely 'unbinned' designation, marked as zero, and the other bin assignments are random numbers between 1 and 99).  Running the reformatted bin assignments file through graphbin2 finally runs to completion successfully, but of course, the final bin assignments are still erroneous, with just a single bin assignment for all contigs.

Running the metabat2 results through the utility script also doubles the size of the output file compared to the input.  Why?
How can I run metabat2 initial binning results through graphbin2 successfully with meaningful results?

**Comment by Vini2** [comment]
Hello @colin-heberling,

Thanks for your interest in GraphBin2. Can you please provide the following details?

1. Can you post what the converted bin assignments file from sed looks like? 

2. Can you post the exact command you used to run GraphBin2 using the converted bin assignments file?

3. Did you provide the path to where the `.fa` files of the MetaBAT2 result are to `--binned` of `prepResult.py`? Is `$(pwd)` where the `.fa` files of the MetaBAT2 result are?

Thank you!

**Comment by colin-heberling** [comment]
Thanks, number 3 worked.  It was not clear from the documentation that the directory I pointed to with `--binned` had to contain the initial genome bins in fasta format, I thought the contig to bin mappings file was all that was needed, so I was confused that the script called for a full directory rather than a single file.

Everything works now, but now I have a series of new feature requests which I'll place in new issues.
It would be great if you could clarify the need for the fasta files in the documentation.  Should I create a new issue for that, or should we wait to close this issue until that's done?
