### ISSUE TITLE
Feature Request: Re-output contigs to fasta according to new bin assignments?

### ISSUE THREAD

**Issue by colin-heberling** [metagentools/GraphBin2#14]
Most initial binning tools output the contigs to different fasta files, one file per bin.  Graphbin2 provides the new bin assignments, but does not re-output contigs based on the new assignments.  It would be great if it did, so that the user doesn't have to do extra work to do so.

**Comment by Vini2** [comment]
Hi @colin-heberling,

GraphBin2 now outputs FASTA files for each bin, including the sequences assigned to multiple bins. Feel free to give it a try.

Closing this issue.
