### ISSUE TITLE
feature request: select delimiter

### ISSUE THREAD

**Issue by nick-youngblut** [metagentools/GraphBin2#3]
DAS-Tool requires a bin table formatted as: `contig_id<tab>bin_id`, while graphbin2 uses comma-delimited input/output bin tables. It would be helpful if the user could chose the delimiter for the input/output bin tables (especially the output).

**Comment by Vini2** [comment]
Hello @nick-youngblut,

Thank you for the feature request. I will definitely incorporate the delimiter option. Until then, I will leave this issue open.

**Comment by Vini2** [comment]
Added the functionality to specify the delimiter for input/output files. 

Commit ID: [c25a5f8c3d8f00cf6d7b4a187a0108eb27cf4506](https://github.com/Vini2/GraphBin2/commit/c25a5f8c3d8f00cf6d7b4a187a0108eb27cf4506)

Closing issue after reesolving.
