### ISSUE TITLE
Should GraphBin/GraphBin2 operate on the contigs of metaFlye assemblies?

### ISSUE THREAD

**Issue by schorlton** [metagentools/GraphBin2#9]
Hi @Vini2 ,

Thanks for the great tool. More a conceptual question, your manuscripts all discuss binning of contigs, which seems to make sense to me (especially for paired-end Illumina where pairs can link contigs into scaffolds); however the metaFlye implementations operate on _edges_ in the assembly graph. My understanding of metaFlye assembly graph is it is possible to have a contig made of 2 connected edges (eg. A and B) which loops back to 1 of the edges so that the contig may be A -> B -> A. This additional information (ie the longer, more complete contig) may then help the binning software bin the contig, and also lead to more complete bins (else the bin may only have 1 copy of A instead of 2).

Would it not make sense for GraphBin/GraphBin2 to operate on contigs, propagating labels across scaffold links? Unfortunately/fortunately, there are frequently very few or even no scaffold links in metaFlye assemblies (found in the `scaffolds_links.txt` file in `30-contigger` folder in the metaFlye output), and therefore I expect the effect of GraphBin/GraphBin2 to not be as large as for Illumina assemblies. Thanks for your thoughts!

-Sam

**Comment by Vini2** [comment]
Hi @schorlton,

GraphBin/GraphBin2 now supports original contigs from Flye.

Thanks! Closing this issue now. Please re-open if needed.
